-- StudyUSICT: subjects seed (2024 & after / ICT scheme)
-- Re-runnable: clears the table first, then inserts every subject.
DELETE FROM subjects;
INSERT INTO subjects (year_scheme, branch, semester, route, category, code, name, lecture_hours, practical_hours, credits) VALUES
  ('2024_and_after', 'CSE', 1, NULL, 'ES', 'ICT-101', 'Programming for Problem Solving', 3, NULL, 3),
  ('2024_and_after', 'CSE', 1, NULL, 'ES', 'ICT-103', 'Basics of Electrical Engineering', 3, NULL, 3),
  ('2024_and_after', 'CSE', 1, NULL, 'ES', 'ICT-105', 'System Modeling Techniques – I', 3, NULL, 3),
  ('2024_and_after', 'CSE', 1, NULL, 'ES', 'ICT-107', 'Engineering Mechanics', 3, NULL, 3),
  ('2024_and_after', 'CSE', 1, NULL, 'AEC', 'ICT-109', 'Communication Skills', 3, NULL, 3),
  ('2024_and_after', 'CSE', 1, NULL, 'VAC', 'HVEE-113', 'Human Values & Ethics1+', 2, NULL, 2),
  ('2024_and_after', 'CSE', 1, NULL, NULL, 'ICT-111', 'PCB design', 3, NULL, 3),
  ('2024_and_after', 'CSE', 1, NULL, NULL, 'ICT-121', 'Introduction to Manufacturing Process', 3, NULL, 3),
  ('2024_and_after', 'CSE', 1, NULL, 'ES', 'ICT-151', 'Programming for Problem Solving Lab', NULL, 2, 1),
  ('2024_and_after', 'CSE', 1, NULL, 'ES', 'ICT-153', 'Basics of Electrical Engineering Lab', NULL, 2, 1),
  ('2024_and_after', 'CSE', 1, NULL, 'VAC', 'ICT-352', 'NSS/NCC/Cultural Clubs/Technical Society/ Technical Club/Institution’s Innovation Council', NULL, NULL, 2),
  ('2024_and_after', 'CSE', 2, NULL, 'ES', 'ICT-102', 'Data Structures', 3, NULL, 3),
  ('2024_and_after', 'CSE', 2, NULL, 'SEC', 'ICT-104', 'Python Programming', 3, NULL, 3),
  ('2024_and_after', 'CSE', 2, NULL, 'ES', 'ICT-106', 'Digital Electronics and Computer Organization', 3, NULL, 3),
  ('2024_and_after', 'CSE', 2, NULL, 'ES', 'ICT-108', 'System Modeling Techniques - II', 3, NULL, 3),
  ('2024_and_after', 'CSE', 2, NULL, 'ES', 'ICT-110', 'Semiconductor Engineering and its applications', 3, NULL, 3),
  ('2024_and_after', 'CSE', 2, NULL, 'VAC', 'ICT-112', 'Environment Studies#+', 2, NULL, 2),
  ('2024_and_after', 'CSE', 2, NULL, 'ES', 'ICT-152', 'Data Structures Lab', NULL, 2, 1),
  ('2024_and_after', 'CSE', 2, NULL, 'SEC', 'ICT-154', 'Python Programming Lab', NULL, 2, 1),
  ('2024_and_after', 'CSE', 2, NULL, 'ES', 'ICT-156', 'Digital Electronics and Computer Organization Lab', NULL, 2, 1),
  ('2024_and_after', 'CSE', 2, NULL, 'ES', 'ICT-158', 'System Modeling Techniques Lab', NULL, 2, 1),
  ('2024_and_after', 'CSE', 2, NULL, 'ES', 'ICT-160', 'Semiconductor Engineering and its applications lab', NULL, 2, 1),
  ('2024_and_after', 'CSE', 3, NULL, 'PC', 'ICT-201', 'Foundations of Computer Science', 4, NULL, 4),
  ('2024_and_after', 'CSE', 3, NULL, 'PC', 'ICT-203', 'Database Management Systems', 3, NULL, 3),
  ('2024_and_after', 'CSE', 3, NULL, 'PC', 'ICT-205', 'Object Oriented Programming using C++', 3, NULL, 3),
  ('2024_and_after', 'CSE', 3, NULL, 'PC', 'ICT-207', 'Design and Analysis of Algorithms', 3, NULL, 3),
  ('2024_and_after', 'CSE', 3, NULL, NULL, 'ICT-217T', 'Digital Signal processing - I', 2, NULL, 2),
  ('2024_and_after', 'CSE', 3, NULL, NULL, 'ICT-217P', 'Digital Signal Processing Laboratory - I', NULL, 2, 1),
  ('2024_and_after', 'CSE', 3, NULL, NULL, 'ICT-219T', 'Digital System Design – I', 2, NULL, 2),
  ('2024_and_after', 'CSE', 3, NULL, NULL, 'ICT-219P', 'Digital System Design – I Lab', NULL, 2, 1),
  ('2024_and_after', 'CSE', 3, NULL, NULL, 'ICT-221', 'Engineering Electromagnetics', 3, NULL, 3),
  ('2024_and_after', 'CSE', 3, NULL, NULL, 'ICT-223T', 'Microprocessor and Interfacing - I', 2, NULL, 2),
  ('2024_and_after', 'CSE', 3, NULL, NULL, 'ICT-223P', 'Microprocessor and Interfacing – I Laboratory', NULL, 2, 1),
  ('2024_and_after', 'CSE', 3, NULL, 'BS', 'ICT-209', 'Engineering Physics', NULL, NULL, NULL),
  ('2024_and_after', 'CSE', 3, NULL, 'BS', 'ICT-211', 'Engineering Chemistry', NULL, NULL, NULL),
  ('2024_and_after', 'CSE', 3, NULL, 'PCE', 'ICT-213', 'Computational Methods', NULL, NULL, NULL),
  ('2024_and_after', 'CSE', 3, NULL, 'PCE', 'ICT-215', 'Computer Graphics', NULL, NULL, NULL),
  ('2024_and_after', 'CSE', 3, NULL, 'PC', 'ICT-251', 'Database Management Systems Lab', NULL, 2, 1),
  ('2024_and_after', 'CSE', 3, NULL, 'PC', 'ICT-253', 'Object Oriented Programming using C++', NULL, 2, 1),
  ('2024_and_after', 'CSE', 3, NULL, 'PC', 'ICT-255', 'Design and Analysis of Algorithms Lab', NULL, 2, 1),
  ('2024_and_after', 'CSE', 3, NULL, 'BS', 'ICT-257', 'Engineering Chemistry Lab', NULL, NULL, NULL),
  ('2024_and_after', 'CSE', 3, NULL, 'BS', 'ICT-259', 'Engineering Physics Lab', NULL, NULL, NULL),
  ('2024_and_after', 'CSE', 3, NULL, 'PCE', 'ICT-261', 'Computational Methods Lab', NULL, NULL, NULL),
  ('2024_and_after', 'CSE', 3, NULL, 'PCE', 'ICT-263', 'Computer Graphics Lab', NULL, NULL, NULL),
  ('2024_and_after', 'CSE', 4, NULL, 'PC', 'ICT-202', 'Theory of Computation', 3, NULL, 3),
  ('2024_and_after', 'CSE', 4, NULL, 'PC', 'ICT-204', 'Probability and Stochastic Systems for Engineers', 3, NULL, 3),
  ('2024_and_after', 'CSE', 4, NULL, 'PC', 'ICT-206', 'Computer Networks', 3, NULL, 3),
  ('2024_and_after', 'CSE', 4, NULL, 'PC', 'ICT-208', 'Operating Systems', 3, NULL, 3),
  ('2024_and_after', 'CSE', 4, NULL, NULL, 'ICT-214T', 'Digital Signal Processing – II', 2, NULL, 2),
  ('2024_and_after', 'CSE', 4, NULL, NULL, 'ICT-214P', 'Digital Signal Processing – II Laboratory', NULL, 2, 1),
  ('2024_and_after', 'CSE', 4, NULL, NULL, 'ICT-216T', 'Digital System Design – II', 2, NULL, 2),
  ('2024_and_after', 'CSE', 4, NULL, NULL, 'ICT-216P', 'Digital System Design – II Lab', NULL, 2, 1),
  ('2024_and_after', 'CSE', 4, NULL, NULL, 'ICT-218', 'Introduction to Robotics', 3, NULL, 3),
  ('2024_and_after', 'CSE', 4, NULL, NULL, 'ICT-220T', 'Microprocessor and Interfacing – II', 2, NULL, 2),
  ('2024_and_after', 'CSE', 4, NULL, NULL, 'ICT-220P', 'Microprocessor and Interfacing – II Laboratory', NULL, 2, 1),
  ('2024_and_after', 'CSE', 4, NULL, 'VAC', 'HVEE-210', 'Science and Practice of Happiness2', NULL, NULL, 2),
  ('2024_and_after', 'CSE', 4, NULL, 'AEC', 'ICT-212', 'Scientific Writing', 2, NULL, 2),
  ('2024_and_after', 'CSE', 4, NULL, 'PC', 'ICT-252', 'Computer Networks Lab', NULL, 2, 1),
  ('2024_and_after', 'CSE', 4, NULL, 'PC', 'ICT-254', 'Operating Systems Lab', NULL, 2, 1),
  ('2024_and_after', 'CSE', 5, NULL, 'PC', 'ICT-301', 'Compiler Design', 3, NULL, 3),
  ('2024_and_after', 'CSE', 5, NULL, 'PC', 'ICT-303', 'Java Programming', 3, NULL, 3),
  ('2024_and_after', 'CSE', 5, NULL, 'SEC', 'ICT-305', 'Web Development', 3, NULL, 3),
  ('2024_and_after', 'CSE', 5, NULL, 'PC', 'ICT-323', 'Compiler Design Lab', NULL, 2, 1),
  ('2024_and_after', 'CSE', 5, NULL, 'PC', 'ICT-325', 'Java Programming Lab', NULL, 2, 1),
  ('2024_and_after', 'CSE', 5, NULL, 'SEC', 'ICT-327', 'Web Development Lab', NULL, 2, 1),
  ('2024_and_after', 'CSE', 5, NULL, 'AEC', 'ICT-321', 'Summer Training (after 4th Semester) Report and Presentation', NULL, NULL, 2),
  ('2024_and_after', 'CSE', 5, NULL, 'AEC', 'ICT-349', 'Summer Project (after 4th Semester) Report and Presentation', NULL, NULL, 2),
  ('2024_and_after', 'CSE', 6, NULL, 'PC', 'ICT-302', 'Software Engineering', 3, NULL, 3),
  ('2024_and_after', 'CSE', 6, NULL, 'PC', 'ICT-324', 'Software Engineering Lab', NULL, 2, 1),
  ('2024_and_after', 'CSE', 6, NULL, 'VAC', 'ICT-322', 'NSS/NCC/Cultural Clubs/Technical Society/ Technical Club/Institution’s Innovation Council', NULL, NULL, 2),
  ('2024_and_after', 'CSE', 7, 'Regular', 'PC', 'ICT-403', 'Minor Project - Report', NULL, NULL, 4),
  ('2024_and_after', 'CSE', 7, 'Regular', 'AEC', 'ICT-401', 'Summer Training (after 6th Semester) Report and Presentation', NULL, NULL, 2),
  ('2024_and_after', 'CSE', 7, 'Regular', 'AEC', 'ICT-449', 'Summer Project (after 6th Semester) Report and Presentation', NULL, NULL, 2),
  ('2024_and_after', 'CSE', 7, 'Research', 'PC / Internship', 'ICT-411', 'Research Work Report – I #', NULL, NULL, 14),
  ('2024_and_after', 'CSE', 7, 'Research', NULL, 'ICT-413', 'Research Work – I Viva Voce', NULL, NULL, 4),
  ('2024_and_after', 'CSE', 7, 'Research', NULL, 'ICT-415', 'Research Work – I Progress Evaluation', NULL, NULL, 2),
  ('2024_and_after', 'CSE', 7, 'Research', 'AEC', 'ICT-401', 'Summer Training (after 6th Semester) Report and Presentation', NULL, NULL, 2),
  ('2024_and_after', 'CSE', 7, 'Research', 'AEC', 'ICT-449', 'Summer Project (after 6th Semester) Report and Presentation', NULL, NULL, 2),
  ('2024_and_after', 'CSE', 8, 'Regular', 'PC / Project', 'ICT-402', 'Major Project – Report', NULL, NULL, 16),
  ('2024_and_after', 'CSE', 8, 'Regular', NULL, 'ICT-404', 'Major Project Viva Voce', NULL, NULL, 4),
  ('2024_and_after', 'CSE', 8, 'Regular', NULL, 'ICT-406', 'Major Project Progress Evaluation', NULL, NULL, 2),
  ('2024_and_after', 'CSE', 8, 'Research', 'PC / Research', 'ICT-414', 'Thesis', NULL, NULL, 16),
  ('2024_and_after', 'CSE', 8, 'Research', NULL, 'ICT-416', 'Internship Viva Voce', NULL, NULL, 4),
  ('2024_and_after', 'CSE', 8, 'Research', NULL, 'ICT-418', 'Internship Progress Evaluation', NULL, NULL, 2),
  ('2024_and_after', 'IT', 1, NULL, 'ES', 'ICT-101', 'Programming for Problem Solving', 3, NULL, 3),
  ('2024_and_after', 'IT', 1, NULL, 'ES', 'ICT-115', 'Digital Electronics and Computer Organization', 3, NULL, 3),
  ('2024_and_after', 'IT', 1, NULL, 'ES', 'ICT-105', 'System Modeling Techniques – I', 3, NULL, 3),
  ('2024_and_after', 'IT', 1, NULL, 'ES', 'ICT-117', 'Semiconductor Engineering and its applications', 3, NULL, 3),
  ('2024_and_after', 'IT', 1, NULL, 'AEC', 'ICT-109', 'Communication Skills', 3, NULL, 3),
  ('2024_and_after', 'IT', 1, NULL, 'VAC', 'ICT-113', 'Human Values & Ethics1+', 2, NULL, 2),
  ('2024_and_after', 'IT', 1, NULL, NULL, 'ICT-111', 'PCB design', 3, NULL, 3),
  ('2024_and_after', 'IT', 1, NULL, NULL, 'ICT-121', 'Introduction to Manufacturing Process', 3, NULL, 3),
  ('2024_and_after', 'IT', 1, NULL, 'ES', 'ICT-151', 'Programming for Problem Solving Lab', NULL, 2, 1),
  ('2024_and_after', 'IT', 1, NULL, 'ES', 'ICT-155', 'Digital Electronics and Computer Organization Lab', NULL, 2, 1),
  ('2024_and_after', 'IT', 1, NULL, 'ES', 'ICT-157', 'Semiconductor Engineering and its applications', NULL, 2, 1),
  ('2024_and_after', 'IT', 1, NULL, 'VAC', 'ICT-352', 'NSS/NCC/Cultural Clubs/Technical Society/ Technical Club/Institution’s Innovation Council', NULL, NULL, 2),
  ('2024_and_after', 'IT', 2, NULL, 'ES', 'ICT-102', 'Data Structures', 3, NULL, 3),
  ('2024_and_after', 'IT', 2, NULL, 'SEC', 'ICT-104', 'Python Programming', 3, NULL, 3),
  ('2024_and_after', 'IT', 2, NULL, 'ES', 'ICT-118', 'Basics of Electrical Engineering', 3, NULL, 3),
  ('2024_and_after', 'IT', 2, NULL, 'ES', 'ICT-108', 'System Modeling Techniques - II', 3, NULL, 3),
  ('2024_and_after', 'IT', 2, NULL, 'ES', 'ICT-120', 'Engineering Mechanics', 3, NULL, 3),
  ('2024_and_after', 'IT', 2, NULL, 'VAC', 'ICT-112', 'Environment Studies#+', 2, NULL, 2),
  ('2024_and_after', 'IT', 2, NULL, 'ES', 'ICT-152', 'Data Structures Lab', NULL, 2, 1),
  ('2024_and_after', 'IT', 2, NULL, 'SEC', 'ICT-154', 'Python Programming Lab', NULL, 2, 1),
  ('2024_and_after', 'IT', 2, NULL, 'ES', 'ICT-162', 'Basics of Electrical Engineering Lab', NULL, 2, 1),
  ('2024_and_after', 'IT', 2, NULL, 'ES', 'ICT-158', 'System Modeling Techniques Lab', NULL, 2, 1),
  ('2024_and_after', 'IT', 3, NULL, 'PC', 'ICT-201', 'Foundations of Computer Science', 4, NULL, 4),
  ('2024_and_after', 'IT', 3, NULL, 'PC', 'ICT-203', 'Database Management Systems', 3, NULL, 3),
  ('2024_and_after', 'IT', 3, NULL, 'PC', 'ICT-205', 'Object Oriented Programming using C++', 3, NULL, 3),
  ('2024_and_after', 'IT', 3, NULL, 'PC', 'ICT-207', 'Design and Analysis of Algorithms', 3, NULL, 3),
  ('2024_and_after', 'IT', 3, NULL, NULL, 'ICT-217T', 'Digital Signal processing - I', 2, NULL, 2),
  ('2024_and_after', 'IT', 3, NULL, NULL, 'ICT-217P', 'Digital Signal Processing Laboratory - I', NULL, 2, 1),
  ('2024_and_after', 'IT', 3, NULL, NULL, 'ICT-219T', 'Digital System Design – I', 2, NULL, 2),
  ('2024_and_after', 'IT', 3, NULL, NULL, 'ICT-219P', 'Digital System Design – I Lab', NULL, 2, 1),
  ('2024_and_after', 'IT', 3, NULL, NULL, 'ICT-221', 'Engineering Electromagnetcis', 3, NULL, 3),
  ('2024_and_after', 'IT', 3, NULL, NULL, 'ICT-223T', 'Microprocessor and Interfacing - I', 2, NULL, 2),
  ('2024_and_after', 'IT', 3, NULL, NULL, 'ICT-223P', 'Microprocessor and Interfacing – I Laboratory', NULL, 2, 1),
  ('2024_and_after', 'IT', 3, NULL, 'PC', 'ICT-225', 'Probability and Stochastic Systems for Engineers', 3, NULL, 3),
  ('2024_and_after', 'IT', 3, NULL, 'PC', 'ICT-251', 'Database Management Systems Lab', NULL, 2, 1),
  ('2024_and_after', 'IT', 3, NULL, 'PC', 'ICT-253', 'Object Oriented Programming using C++', NULL, 2, 1),
  ('2024_and_after', 'IT', 3, NULL, 'PC', 'ICT-255', 'Design and Analysis of Algorithms Lab', NULL, 2, 1),
  ('2024_and_after', 'IT', 4, NULL, 'PC', 'ICT-202', 'Theory of Computation', 3, NULL, 3),
  ('2024_and_after', 'IT', 4, NULL, 'PC', 'ICT-208', 'Operating Systems', 3, NULL, 3),
  ('2024_and_after', 'IT', 4, NULL, NULL, 'ICT-214T', 'Digital Signal Processing – II', 2, NULL, 2),
  ('2024_and_after', 'IT', 4, NULL, NULL, 'ICT-214P', 'Digital Signal Processing – II Laboratory', NULL, 2, 1),
  ('2024_and_after', 'IT', 4, NULL, NULL, 'ICT-216T', 'Digital System Design – II', 2, NULL, 2),
  ('2024_and_after', 'IT', 4, NULL, NULL, 'ICT-216P', 'Digital System Design – II Lab', NULL, 2, 1),
  ('2024_and_after', 'IT', 4, NULL, NULL, 'ICT-218', 'Introduction to Robotics', 3, NULL, 3),
  ('2024_and_after', 'IT', 4, NULL, NULL, 'ICT-220T', 'Microprocessor and Interfacing – II', 2, NULL, 2),
  ('2024_and_after', 'IT', 4, NULL, NULL, 'ICT-220P', 'Microprocessor and Interfacing – II Laboratory', NULL, 2, 1),
  ('2024_and_after', 'IT', 4, NULL, 'VAC', 'ICT-210', 'Science and Practice of Happiness2', 2, NULL, 2),
  ('2024_and_after', 'IT', 4, NULL, 'AEC', 'ICT-212', 'Scientific Writing', 2, NULL, 2),
  ('2024_and_after', 'IT', 4, NULL, 'BS', 'ICT-224', 'Engineering Physics', NULL, NULL, NULL),
  ('2024_and_after', 'IT', 4, NULL, 'BS', 'ICT-226', 'Engineering Chemistry', NULL, NULL, NULL),
  ('2024_and_after', 'IT', 4, NULL, 'PCE', 'ICT-228', 'Computational Methods', NULL, NULL, NULL),
  ('2024_and_after', 'IT', 4, NULL, 'PCE', 'ICT-230', 'Computer Graphics', NULL, NULL, NULL),
  ('2024_and_after', 'IT', 4, NULL, 'SEC', 'ICT-222', 'Web Development', 3, NULL, 3),
  ('2024_and_after', 'IT', 4, NULL, 'PC', 'ICT-254', 'Operating Systems Lab', NULL, 2, 1),
  ('2024_and_after', 'IT', 4, NULL, 'PC', 'ICT-264', 'Web Development Lab', NULL, 2, 1),
  ('2024_and_after', 'IT', 4, NULL, 'BS', 'ICT-256', 'Engineering Chemistry Lab', NULL, NULL, NULL),
  ('2024_and_after', 'IT', 4, NULL, 'BS', 'ICT-258', 'Engineering Physics Lab', NULL, NULL, NULL),
  ('2024_and_after', 'IT', 4, NULL, 'PCE', 'ICT-260', 'Computational Methods Lab', NULL, NULL, NULL),
  ('2024_and_after', 'IT', 4, NULL, 'PCE', 'ICT-262', 'Computer Graphics Lab', NULL, NULL, NULL),
  ('2024_and_after', 'IT', 5, NULL, 'PC', 'ICT-301', 'Compiler Design', 3, NULL, 3),
  ('2024_and_after', 'IT', 5, NULL, 'PC', 'ICT-303', 'Java Programming', 3, NULL, 3),
  ('2024_and_after', 'IT', 5, NULL, 'SEC', 'ICT-307', 'Computer Networks', 3, NULL, 3),
  ('2024_and_after', 'IT', 5, NULL, 'PC', 'ICT-323', 'Compiler Design Lab', NULL, 2, 1),
  ('2024_and_after', 'IT', 5, NULL, 'PC', 'ICT-325', 'Java Programming Lab', NULL, 2, 1),
  ('2024_and_after', 'IT', 5, NULL, 'SEC', 'ICT-329', 'Computer Networks Lab', NULL, 2, 1),
  ('2024_and_after', 'IT', 5, NULL, 'AEC', 'ICT-321', 'Summer Training (after 4th Semester) Report and Presentation', NULL, NULL, 2),
  ('2024_and_after', 'IT', 5, NULL, 'AEC', 'ICT-349', 'Summer Project (after 4th Semester) Report and Presentation', NULL, NULL, 2),
  ('2024_and_after', 'IT', 6, NULL, 'PC', 'ICT-302', 'Software Engineering', 3, NULL, 3),
  ('2024_and_after', 'IT', 6, NULL, 'PC', 'ICT-324', 'Software Engineering Lab', NULL, 2, 1),
  ('2024_and_after', 'IT', 6, NULL, 'VAC', 'ICT-322', 'NSS/NCC/Cultural Clubs/Technical Society/ Technical Club/Institution’s Innovation Council', NULL, NULL, 2),
  ('2024_and_after', 'IT', 7, 'Regular', 'PC', 'ICT-403', 'Minor Project - Report', NULL, NULL, 4),
  ('2024_and_after', 'IT', 7, 'Regular', 'AEC', 'ICT-401', 'Summer Training (after 6th Semester) Report and Presentation', NULL, NULL, 2),
  ('2024_and_after', 'IT', 7, 'Regular', 'AEC', 'ICT-449', 'Summer Project (after 6th Semester) Report and Presentation', NULL, NULL, 2),
  ('2024_and_after', 'IT', 7, 'Research', 'PC / Internship', 'ICT-411', 'Research Work Report – I #', NULL, NULL, 14),
  ('2024_and_after', 'IT', 7, 'Research', NULL, 'ICT-413', 'Research Work – I Viva Voce', NULL, NULL, 4),
  ('2024_and_after', 'IT', 7, 'Research', NULL, 'ICT-415', 'Research Work – I Progress Evaluation', NULL, NULL, 2),
  ('2024_and_after', 'IT', 7, 'Research', 'AEC', 'ICT-401', 'Summer Training (after 6th Semester) Report and Presentation', NULL, NULL, 2),
  ('2024_and_after', 'IT', 7, 'Research', 'AEC', 'ICT-449', 'Summer Project (after 6th Semester) Report and Presentation', NULL, NULL, 2),
  ('2024_and_after', 'IT', 8, 'Regular', 'PC / Project', 'ICT-402', 'Major Project – Report', NULL, NULL, 16),
  ('2024_and_after', 'IT', 8, 'Regular', NULL, 'ICT-404', 'Major Project Viva Voce', NULL, NULL, 4),
  ('2024_and_after', 'IT', 8, 'Regular', NULL, 'ICT-406', 'Major Project Progress Evaluation', NULL, NULL, 2),
  ('2024_and_after', 'IT', 8, 'Research', 'PC / Internship', 'ICT-414', 'Thesis', NULL, NULL, 16),
  ('2024_and_after', 'IT', 8, 'Research', NULL, 'ICT-416', 'Internship Viva Voce', NULL, NULL, 4),
  ('2024_and_after', 'IT', 8, 'Research', NULL, 'ICT-418', 'Internship Progress Evaluation', NULL, NULL, 2),
  ('2024_and_after', 'ECE', 1, NULL, 'ES', 'ICT-101', 'Programming for Problem Solving', 3, NULL, 3),
  ('2024_and_after', 'ECE', 1, NULL, 'ES', 'ICT-115', 'Digital Electronics and Computer Organization', 3, NULL, 3),
  ('2024_and_after', 'ECE', 1, NULL, 'ES', 'ICT-105', 'System Modeling Techniques – I', 3, NULL, 3),
  ('2024_and_after', 'ECE', 1, NULL, 'ES', 'ICT-117', 'Semiconductor Engineering and its applications', 3, NULL, 3),
  ('2024_and_after', 'ECE', 1, NULL, 'AEC', 'ICT-109', 'Communication Skills', 3, NULL, 3),
  ('2024_and_after', 'ECE', 1, NULL, 'VAC', 'ICT-113', 'Human Values & Ethics1+', 2, NULL, 2),
  ('2024_and_after', 'ECE', 1, NULL, NULL, 'ICT-119T', 'Programming in C++', 2, NULL, 2),
  ('2024_and_after', 'ECE', 1, NULL, NULL, 'ICT-119P', 'Programming in C++ Lab', NULL, 2, 1),
  ('2024_and_after', 'ECE', 1, NULL, NULL, 'ICT-121', 'Introduction to Manufacturing Process', 3, NULL, 3),
  ('2024_and_after', 'ECE', 1, NULL, 'ES', 'ICT-151', 'Programming for Problem Solving Lab', NULL, 2, 1),
  ('2024_and_after', 'ECE', 1, NULL, 'ES', 'ICT-155', 'Digital Electronics and Computer Organization Lab', NULL, 2, 1),
  ('2024_and_after', 'ECE', 1, NULL, 'ES', 'ICT-157', 'Semiconductor Engineering and its applications', NULL, 2, 1),
  ('2024_and_after', 'ECE', 1, NULL, 'VAC', 'ICT-352', 'NSS/NCC/Cultural Clubs/Technical Society/ Technical Club/Institution’s Innovation Council', NULL, NULL, 2),
  ('2024_and_after', 'ECE', 2, NULL, 'ES', 'ICT-102', 'Data Structures', 3, NULL, 3),
  ('2024_and_after', 'ECE', 2, NULL, 'SEC', 'ICT-104', 'Python Programming', 3, NULL, 3),
  ('2024_and_after', 'ECE', 2, NULL, 'ES', 'ICT-118', 'Basics of Electrical Engineering', 3, NULL, 3),
  ('2024_and_after', 'ECE', 2, NULL, 'ES', 'ICT-108', 'System Modeling Techniques - II', 3, NULL, 3),
  ('2024_and_after', 'ECE', 2, NULL, 'ES', 'ICT-120', 'Engineering Mechanics', 3, NULL, 3),
  ('2024_and_after', 'ECE', 2, NULL, 'VAC', 'ICT-112', 'Environment Studies#+', 2, NULL, 2),
  ('2024_and_after', 'ECE', 2, NULL, 'ES', 'ICT-152', 'Data Structures Lab', NULL, 2, 1),
  ('2024_and_after', 'ECE', 2, NULL, 'SEC', 'ICT-154', 'Python Programming Lab', NULL, 2, 1),
  ('2024_and_after', 'ECE', 2, NULL, 'ES', 'ICT-162', 'Basics of Electrical Engineering Lab', NULL, 2, 1),
  ('2024_and_after', 'ECE', 2, NULL, 'ES', 'ICT-158', 'System Modeling Techniques Lab', NULL, 2, 1),
  ('2024_and_after', 'ECE', 3, NULL, 'PC', 'ICT-235', 'Signals and Systems', 3, NULL, 3),
  ('2024_and_after', 'ECE', 3, NULL, 'PC', 'ICT-221', 'Engineering Electromagnetics', 3, NULL, 3),
  ('2024_and_after', 'ECE', 3, NULL, 'PC', 'ICT-237', 'Analog Circuits', 3, NULL, 3),
  ('2024_and_after', 'ECE', 3, NULL, 'PC', 'ICT-239', 'Analog Communications', 3, NULL, 3),
  ('2024_and_after', 'ECE', 3, NULL, NULL, 'ICT-227T', 'Introduction to RDBMS using PostgreSQL', 2, NULL, 2),
  ('2024_and_after', 'ECE', 3, NULL, NULL, 'ICT-227P', 'Introduction to RDBMS using PostgreSQL', NULL, 2, 1),
  ('2024_and_after', 'ECE', 3, NULL, NULL, 'ICT-229T', 'Web Development – I', 2, NULL, 2),
  ('2024_and_after', 'ECE', 3, NULL, NULL, 'ICT-229P', 'Web Development – I Laboratory', NULL, 2, 1),
  ('2024_and_after', 'ECE', 3, NULL, NULL, 'ICT-231', 'Operating Systems', 3, NULL, 3),
  ('2024_and_after', 'ECE', 3, NULL, NULL, 'ICT-233T', 'Java Programming - I', 2, NULL, 2),
  ('2024_and_after', 'ECE', 3, NULL, NULL, 'ICT-233P', 'Java Programming - I Laboratory', NULL, 2, 1),
  ('2024_and_after', 'ECE', 3, NULL, 'PC', 'ICT-225', 'Probability and Stochastic Systems for Engineers', 3, NULL, 3),
  ('2024_and_after', 'ECE', 3, NULL, 'PC', 'ICT-265', 'Engineering Electromagnetics', NULL, 2, 1),
  ('2024_and_after', 'ECE', 3, NULL, 'PC', 'ICT-267', 'Analog Circuits', NULL, 2, 1),
  ('2024_and_after', 'ECE', 3, NULL, 'PC', 'ICT-269', 'Analog Communications', NULL, 2, 1),
  ('2024_and_after', 'ECE', 4, NULL, 'PC', 'ICT-236', 'Network Analysis and Synthesis', 3, NULL, 3),
  ('2024_and_after', 'ECE', 4, NULL, 'PC', 'ICT-238', 'Digital Communications', 3, NULL, 3),
  ('2024_and_after', 'ECE', 4, NULL, NULL, 'ICT-232T', 'Web Development – II', 2, NULL, 2),
  ('2024_and_after', 'ECE', 4, NULL, NULL, 'ICT-232P', 'Web Development – II Laboratory', NULL, 2, 1),
  ('2024_and_after', 'ECE', 4, NULL, NULL, 'ICT-234T', 'Java Programming – II', 2, NULL, 2),
  ('2024_and_after', 'ECE', 4, NULL, NULL, 'ICT-234P', 'Java Programming – II Laboratory', NULL, 2, 1),
  ('2024_and_after', 'ECE', 4, NULL, NULL, 'ICT-218', 'Introduction to Robotics', 3, NULL, 3),
  ('2024_and_after', 'ECE', 4, NULL, 'VAC', 'ICT-210', 'Science and Practice of Happiness2', 2, NULL, 2),
  ('2024_and_after', 'ECE', 4, NULL, 'AEC', 'ICT-212', 'Scientific Writing', 2, NULL, 2),
  ('2024_and_after', 'ECE', 4, NULL, 'BS', 'ICT-226', 'Engineering Physics', NULL, NULL, NULL),
  ('2024_and_after', 'ECE', 4, NULL, 'BS', 'ICT-228', 'Engineering Chemistry', NULL, NULL, NULL),
  ('2024_and_after', 'ECE', 4, NULL, 'PCE', 'ICT-230', 'Computational Methods', NULL, NULL, NULL),
  ('2024_and_after', 'ECE', 4, NULL, 'PCE', 'ICT-242', 'Electronic Instrumentation and Measurement', NULL, NULL, NULL),
  ('2024_and_after', 'ECE', 4, NULL, 'SEC', 'ICT-240', 'Digital Systems Design', 3, NULL, 3),
  ('2024_and_after', 'ECE', 4, NULL, 'PC', 'ICT-266', 'Digital Communications Lab', NULL, 2, 1),
  ('2024_and_after', 'ECE', 4, NULL, 'BS', 'ICT-256', 'Engineering Chemistry Lab', NULL, NULL, NULL),
  ('2024_and_after', 'ECE', 4, NULL, 'BS', 'ICT-258', 'Engineering Physics Lab', NULL, NULL, NULL),
  ('2024_and_after', 'ECE', 4, NULL, 'PCE', 'ICT-260', 'Computational Methods Lab', NULL, NULL, NULL),
  ('2024_and_after', 'ECE', 4, NULL, 'PCE', 'ICT-272', 'Electronic Instrumentation and Measurement Lab', NULL, NULL, NULL),
  ('2024_and_after', 'ECE', 4, NULL, 'PC', 'ICT-268', 'Digital Systems Design Lab', NULL, 2, 1),
  ('2024_and_after', 'ECE', 4, NULL, 'PC', 'ICT-270', 'Network Analysis and Synthesis Lab', NULL, 2, 1),
  ('2024_and_after', 'ECE', 5, NULL, 'PC', 'ICT-313', 'Digital Signal Processing', 3, NULL, 3),
  ('2024_and_after', 'ECE', 5, NULL, 'PC', 'ICT-315', 'Microprocessors and Interfacing', 3, NULL, 3),
  ('2024_and_after', 'ECE', 5, NULL, 'PC', 'ICT-307', 'Computer Networks', 3, NULL, 3),
  ('2024_and_after', 'ECE', 5, NULL, 'PC', 'ICT-335', 'Digital Signal Processing Lab', NULL, 2, 1),
  ('2024_and_after', 'ECE', 5, NULL, 'PC', 'ICT-337', 'Microprocessors and Interfacing Lab', NULL, 2, 1),
  ('2024_and_after', 'ECE', 5, NULL, 'SEC', 'ICT-329', 'Computer Networks', NULL, 2, 1),
  ('2024_and_after', 'ECE', 5, NULL, 'AEC', 'ICT-321', 'Summer Training (after 4th Semester) Report and Presentation', NULL, NULL, 2),
  ('2024_and_after', 'ECE', 5, NULL, 'AEC', 'ICT-349', 'Summer Project (after 4th Semester) Report and Presentation', NULL, NULL, 2),
  ('2024_and_after', 'ECE', 6, NULL, 'PC', 'ICT-316', 'Linear Integrated Circuits', 3, NULL, 3),
  ('2024_and_after', 'ECE', 6, NULL, 'PC', 'ICT-318', 'Control Systems', 3, NULL, 3),
  ('2024_and_after', 'ECE', 6, NULL, 'PC', 'ICT-338', 'Linear Integrated Circuits Lab', NULL, 2, 1),
  ('2024_and_after', 'ECE', 6, NULL, 'PC', 'ICT-340', 'Control Systems Lab', NULL, 2, 1),
  ('2024_and_after', 'ECE', 6, NULL, 'VAC', 'ICT-322', 'NSS/NCC/Cultural Clubs/Technical Society/ Technical Club/Institution’s Innovation Council', NULL, NULL, 2),
  ('2024_and_after', 'ECE', 7, 'Regular', 'AEC', 'ICT-401', 'Summer Training (after 6th Semester) Report and Presentation', NULL, NULL, 2),
  ('2024_and_after', 'ECE', 7, 'Regular', 'AEC', 'ICT-449', 'Summer Project (after 6th Semester) Report and Presentation', NULL, NULL, 2),
  ('2024_and_after', 'ECE', 7, 'Research', 'PC / Internship', 'ICT-411', 'Research Work Report – I #', NULL, NULL, 14),
  ('2024_and_after', 'ECE', 7, 'Research', NULL, 'ICT-413', 'Research Work – I Viva Voce', NULL, NULL, 4),
  ('2024_and_after', 'ECE', 7, 'Research', NULL, 'ICT-415', 'Research Work – I Progress Evaluation', NULL, NULL, 2),
  ('2024_and_after', 'ECE', 7, 'Research', 'AEC', 'ICT-401', 'Summer Training (after 6th Semester) Report and Presentation', NULL, NULL, 2),
  ('2024_and_after', 'ECE', 7, 'Research', 'AEC', 'ICT-449', 'Summer Project (after 6th Semester) Report and Presentation', NULL, NULL, 2),
  ('2024_and_after', 'ECE', 8, 'Regular', 'PC / Project', 'ICT-402', 'Major Project – Report', NULL, NULL, 16),
  ('2024_and_after', 'ECE', 8, 'Regular', NULL, 'ICT-404', 'Major Project Viva Voce', NULL, NULL, 4),
  ('2024_and_after', 'ECE', 8, 'Regular', NULL, 'ICT-406', 'Major Project Progress Evaluation', NULL, NULL, 2),
  ('2024_and_after', 'ECE', 8, 'Research', 'PC / Research', 'ICT-414', 'Thesis', NULL, NULL, 16),
  ('2024_and_after', 'ECE', 8, 'Research', NULL, 'ICT-416', 'Internship Viva Voce', NULL, NULL, 4),
  ('2024_and_after', 'ECE', 8, 'Research', NULL, 'ICT-418', 'Internship Progress Evaluation', NULL, NULL, 2),
  ('2024_and_after', 'CSAI', 1, NULL, 'ES', 'ICT-101', 'Programming for Problem Solving', 3, NULL, 3),
  ('2024_and_after', 'CSAI', 1, NULL, 'ES', 'ICT-103', 'Basics of Electrical Engineering', 3, NULL, 3),
  ('2024_and_after', 'CSAI', 1, NULL, 'ES', 'ICT-105', 'System Modeling Techniques – I', 3, NULL, 3),
  ('2024_and_after', 'CSAI', 1, NULL, 'ES', 'ICT-107', 'Engineering Mechanics', 3, NULL, 3),
  ('2024_and_after', 'CSAI', 1, NULL, 'AEC', 'ICT-109', 'Communication Skills', 3, NULL, 3),
  ('2024_and_after', 'CSAI', 1, NULL, 'VAC', 'HVEE-113', 'Human Values & Ethics1+', 2, NULL, 2),
  ('2024_and_after', 'CSAI', 1, NULL, NULL, 'ICT-111', 'PCB design', 3, NULL, 3),
  ('2024_and_after', 'CSAI', 1, NULL, NULL, 'ICT-121', 'Introduction to Manufacturing Process', 3, NULL, 3),
  ('2024_and_after', 'CSAI', 1, NULL, 'ES', 'ICT-151', 'Programming for Problem Solving Lab', NULL, 2, 1),
  ('2024_and_after', 'CSAI', 1, NULL, 'ES', 'ICT-153', 'Basics of Electrical Engineering Lab', NULL, 2, 1),
  ('2024_and_after', 'CSAI', 1, NULL, 'VAC', 'ICT-352', 'NSS/NCC/Cultural Clubs/Technical Society/ Technical Club/Institution’s Innovation Council', NULL, NULL, 2),
  ('2024_and_after', 'CSAI', 2, NULL, 'ES', 'ICT-102', 'Data Structures', 3, NULL, 3),
  ('2024_and_after', 'CSAI', 2, NULL, 'SEC', 'ICT-104', 'Python Programming', 3, NULL, 3),
  ('2024_and_after', 'CSAI', 2, NULL, 'ES', 'ICT-106', 'Digital Electronics and Computer Organization', 3, NULL, 3),
  ('2024_and_after', 'CSAI', 2, NULL, 'ES', 'ICT-108', 'System Modeling Techniques - II', 3, NULL, 3),
  ('2024_and_after', 'CSAI', 2, NULL, 'ES', 'ICT-110', 'Semiconductor Engineering and its applications', 3, NULL, 3),
  ('2024_and_after', 'CSAI', 2, NULL, 'VAC', 'ICT-112', 'Environment Studies#+', 2, NULL, 2),
  ('2024_and_after', 'CSAI', 2, NULL, 'ES', 'ICT-152', 'Data Structures Lab', NULL, 2, 1),
  ('2024_and_after', 'CSAI', 2, NULL, 'SEC', 'ICT-154', 'Python Programming Lab', NULL, 2, 1),
  ('2024_and_after', 'CSAI', 2, NULL, 'ES', 'ICT-156', 'Digital Electronics and Computer Organization Lab', NULL, 2, 1),
  ('2024_and_after', 'CSAI', 2, NULL, 'ES', 'ICT-158', 'System Modeling Techniques Lab', NULL, 2, 1),
  ('2024_and_after', 'CSAI', 2, NULL, 'ES', 'ICT-160', 'Semiconductor Engineering and its applications lab', NULL, 2, 1),
  ('2024_and_after', 'CSAI', 3, NULL, 'PC', 'ICT-201', 'Foundations of Computer Science', 4, NULL, 4),
  ('2024_and_after', 'CSAI', 3, NULL, 'PC', 'ICT-203', 'Database Management Systems', 3, NULL, 3),
  ('2024_and_after', 'CSAI', 3, NULL, 'PC', 'ICT-205', 'Object Oriented Programming using C++', 3, NULL, 3),
  ('2024_and_after', 'CSAI', 3, NULL, 'PC', 'ICT-207', 'Design and Analysis of Algorithms', 3, NULL, 3),
  ('2024_and_after', 'CSAI', 3, NULL, NULL, 'ICT-217T', 'Digital Signal processing - I', 2, NULL, 2),
  ('2024_and_after', 'CSAI', 3, NULL, NULL, 'ICT-217P', 'Digital Signal Processing Laboratory - I', NULL, 2, 1),
  ('2024_and_after', 'CSAI', 3, NULL, NULL, 'ICT-219T', 'Digital System Design – I', 2, NULL, 2),
  ('2024_and_after', 'CSAI', 3, NULL, NULL, 'ICT-219P', 'Digital System Design – I Lab', NULL, 2, 1),
  ('2024_and_after', 'CSAI', 3, NULL, NULL, 'ICT-221', 'Engineering Electromagnetics', 3, NULL, 3),
  ('2024_and_after', 'CSAI', 3, NULL, NULL, 'ICT-223T', 'Microprocessor and Interfacing - I', 2, NULL, 2),
  ('2024_and_after', 'CSAI', 3, NULL, NULL, 'ICT-223P', 'Microprocessor and Interfacing – I Laboratory', NULL, 2, 1),
  ('2024_and_after', 'CSAI', 3, NULL, 'BS', 'ICT-209', 'Engineering Physics', NULL, NULL, NULL),
  ('2024_and_after', 'CSAI', 3, NULL, 'BS', 'ICT-211', 'Engineering Chemistry', NULL, NULL, NULL),
  ('2024_and_after', 'CSAI', 3, NULL, 'PCE', 'ICT-213', 'Computational Methods', NULL, NULL, NULL),
  ('2024_and_after', 'CSAI', 3, NULL, 'PCE', 'ICT-215', 'Computer Graphics', NULL, NULL, NULL),
  ('2024_and_after', 'CSAI', 3, NULL, 'PC', 'ICT-251', 'Database Management Systems Lab', NULL, 2, 1),
  ('2024_and_after', 'CSAI', 3, NULL, 'PC', 'ICT-253', 'Object Oriented Programming using C++', NULL, 2, 1),
  ('2024_and_after', 'CSAI', 3, NULL, 'PC', 'ICT-255', 'Design and Analysis of Algorithms Lab', NULL, 2, 1),
  ('2024_and_after', 'CSAI', 3, NULL, 'BS', 'ICT-257', 'Engineering Chemistry Lab', NULL, NULL, NULL),
  ('2024_and_after', 'CSAI', 3, NULL, 'BS', 'ICT-259', 'Engineering Physics Lab', NULL, NULL, NULL),
  ('2024_and_after', 'CSAI', 3, NULL, 'PCE', 'ICT-261', 'Computational Methods Lab', NULL, NULL, NULL),
  ('2024_and_after', 'CSAI', 3, NULL, 'PCE', 'ICT-263', 'Computer Graphics Lab', NULL, NULL, NULL),
  ('2024_and_after', 'CSAI', 4, NULL, 'PC', 'ICT-202', 'Theory of Computation', 3, NULL, 3),
  ('2024_and_after', 'CSAI', 4, NULL, 'PC', 'ICT-204', 'Probability and Stochastic Systems for Engineers', 3, NULL, 3),
  ('2024_and_after', 'CSAI', 4, NULL, 'PC', 'ICT-206', 'Computer Networks', 3, NULL, 3),
  ('2024_and_after', 'CSAI', 4, NULL, 'PC', 'ICT-208', 'Operating Systems', 3, NULL, 3),
  ('2024_and_after', 'CSAI', 4, NULL, NULL, 'ICT-214T', 'Digital Signal Processing – II', 2, NULL, 2),
  ('2024_and_after', 'CSAI', 4, NULL, NULL, 'ICT-214P', 'Digital Signal Processing – II Laboratory', NULL, 2, 1),
  ('2024_and_after', 'CSAI', 4, NULL, NULL, 'ICT-216T', 'Digital System Design – II', 2, NULL, 2),
  ('2024_and_after', 'CSAI', 4, NULL, NULL, 'ICT-216P', 'Digital System Design – II Lab', NULL, 2, 1),
  ('2024_and_after', 'CSAI', 4, NULL, NULL, 'ICT-218', 'Introduction to Robotics', 3, NULL, 3),
  ('2024_and_after', 'CSAI', 4, NULL, NULL, 'ICT-220T', 'Microprocessor and Interfacing – II', 2, NULL, 2),
  ('2024_and_after', 'CSAI', 4, NULL, NULL, 'ICT-220P', 'Microprocessor and Interfacing – II Laboratory', NULL, 2, 1),
  ('2024_and_after', 'CSAI', 4, NULL, 'VAC', 'ICT-210', 'Science and Practice of Happiness2', NULL, NULL, 2),
  ('2024_and_after', 'CSAI', 4, NULL, 'AEC', 'ICT-212', 'Scientific Writing', 2, NULL, 2),
  ('2024_and_after', 'CSAI', 4, NULL, 'PC', 'ICT-252', 'Computer Networks Lab', NULL, 2, 1),
  ('2024_and_after', 'CSAI', 4, NULL, 'PC', 'ICT-254', 'Operating Systems Lab', NULL, 2, 1),
  ('2024_and_after', 'CSAI', 5, NULL, 'PC', 'ICT-301', 'Compiler Design', 3, NULL, 3),
  ('2024_and_after', 'CSAI', 5, NULL, 'PC', 'ICT-303', 'Java Programming', 3, NULL, 3),
  ('2024_and_after', 'CSAI', 5, NULL, 'SEC', 'ICT-305', 'Web Development', 3, NULL, 3),
  ('2024_and_after', 'CSAI', 5, NULL, 'PC', 'ICT-307', 'Artificial Intelligence & Knowledge Based Systems', 3, NULL, 3),
  ('2024_and_after', 'CSAI', 5, NULL, 'PC', 'ICT-309', 'Fundamentals of Machine Learning & Neural Networks', 3, NULL, 3),
  ('2024_and_after', 'CSAI', 5, NULL, 'PC', 'ICT-323', 'Compiler Design Lab', NULL, 2, 1),
  ('2024_and_after', 'CSAI', 5, NULL, 'PC', 'ICT-325', 'Java Programming Lab', NULL, 2, 1),
  ('2024_and_after', 'CSAI', 5, NULL, 'SEC', 'ICT-327', 'Web Development Lab', NULL, 2, 1),
  ('2024_and_after', 'CSAI', 5, NULL, 'PC', 'ICT-329', 'Artificial Intelligence & Knowledge Based Systems Lab', NULL, 2, 1),
  ('2024_and_after', 'CSAI', 5, NULL, 'PC', 'ICT-331', 'Fundamentals of Machine Learning & Neural Networks Lab', NULL, 2, 1),
  ('2024_and_after', 'CSAI', 5, NULL, 'AEC', 'ICT-321', 'Summer Training (after 4th Semester) Report and Presentation', NULL, NULL, 2),
  ('2024_and_after', 'CSAI', 5, NULL, 'AEC', 'ICT-349', 'Summer Project (after 4th Semester) Report and Presentation', NULL, NULL, 2),
  ('2024_and_after', 'CSAI', 6, NULL, 'PC', 'ICT-302', 'Software Engineering', 3, NULL, 3),
  ('2024_and_after', 'CSAI', 6, NULL, 'PC', 'ICT-304', 'Optimization Techniques for Machine Learning', 3, NULL, 3),
  ('2024_and_after', 'CSAI', 6, NULL, 'PC', 'ICT-306', 'Deep Learning', 3, NULL, 3),
  ('2024_and_after', 'CSAI', 6, NULL, 'PC', 'ICT-308', 'Search-based methods for Machine Learning', 3, NULL, 3),
  ('2024_and_after', 'CSAI', 6, NULL, 'PC', 'ICT-310', 'Reinforcement Learning and Sequential Decision Making', 3, NULL, 3),
  ('2024_and_after', 'CSAI', 6, NULL, 'PC', 'ICT-324', 'Software Engineering Lab', NULL, 2, 1),
  ('2024_and_after', 'CSAI', 6, NULL, 'PC', 'ICT-326', 'Optimization Techniques for Machine Learning Lab', NULL, 2, 1),
  ('2024_and_after', 'CSAI', 6, NULL, 'PC', 'ICT-328', 'Deep Learning Lab', NULL, 2, 1),
  ('2024_and_after', 'CSAI', 6, NULL, 'PC', 'ICT-330', 'Search-based methods for Machine Learning Lab', NULL, 2, 1),
  ('2024_and_after', 'CSAI', 6, NULL, 'PC', 'ICT-332', 'Reinforcement Learning and Sequential Decision Making Lab', NULL, 2, 1),
  ('2024_and_after', 'CSAI', 6, NULL, 'VAC', 'ICT-322', 'NSS/NCC/Cultural Clubs/Technical Society/ Technical Club/Institution’s Innovation Council', NULL, NULL, 2),
  ('2024_and_after', 'CSAI', 7, 'Regular', 'PC', 'ICT-417T', 'Natural Language Processing and Large Language Models', 3, NULL, 3),
  ('2024_and_after', 'CSAI', 7, 'Regular', NULL, 'ICT-417P', 'Natural Language Processing and Large Language Models Lab', NULL, 2, 1),
  ('2024_and_after', 'CSAI', 7, 'Regular', 'PC', 'ICT-419T', 'Probabilistic Graphical Models and Inference', 3, NULL, 3),
  ('2024_and_after', 'CSAI', 7, 'Regular', NULL, 'ICT-419P', 'Probabilistic Graphical Models and Inference Lab', NULL, 2, 1),
  ('2024_and_after', 'CSAI', 7, 'Regular', 'PC', 'ICT-403', 'Minor Project - Report', NULL, NULL, 4),
  ('2024_and_after', 'CSAI', 7, 'Regular', 'AEC', 'ICT-321', 'Summer Training (after 6th Semester) Report and Presentation', NULL, NULL, 2),
  ('2024_and_after', 'CSAI', 7, 'Regular', 'AEC', 'ICT-349', 'Summer Project (after 6th Semester) Report and Presentation', NULL, NULL, 2),
  ('2024_and_after', 'CSAI', 7, 'Research', 'PC / Internship', 'ICT-411', 'Research Work Report – I #', NULL, NULL, 14),
  ('2024_and_after', 'CSAI', 7, 'Research', NULL, 'ICT-413', 'Research Work – I Viva Voce', NULL, NULL, 4),
  ('2024_and_after', 'CSAI', 7, 'Research', NULL, 'ICT-415', 'Research Work – I Progress Evaluation', NULL, NULL, 2),
  ('2024_and_after', 'CSAI', 7, 'Research', 'AEC', 'ICT-401', 'Summer Training (after 6th Semester) Report and Presentation', NULL, NULL, 2),
  ('2024_and_after', 'CSAI', 7, 'Research', 'AEC', 'ICT-449', 'Summer Project (after 6th Semester) Report and Presentation', NULL, NULL, 2),
  ('2024_and_after', 'CSAI', 8, 'Regular', 'PC / Project', 'ICT-402', 'Major Project – Report', NULL, NULL, 16),
  ('2024_and_after', 'CSAI', 8, 'Regular', NULL, 'ICT-404', 'Major Project Viva Voce', NULL, NULL, 4),
  ('2024_and_after', 'CSAI', 8, 'Regular', NULL, 'ICT-406', 'Major Project Progress Evaluation', NULL, NULL, 2),
  ('2024_and_after', 'CSAI', 8, 'Research', 'PC / Internship', 'ICT-414', 'Thesis', NULL, NULL, 16),
  ('2024_and_after', 'CSAI', 8, 'Research', NULL, 'ICT-416', 'Internship Viva Voce', NULL, NULL, 4),
  ('2024_and_after', 'CSAI', 8, 'Research', NULL, 'ICT-418', 'Internship Progress Evaluation', NULL, NULL, 2),
  ('2024_and_after', 'CSDS', 1, NULL, 'ES', 'ICT-101', 'Programming for Problem Solving', 3, NULL, 3),
  ('2024_and_after', 'CSDS', 1, NULL, 'ES', 'ICT-103', 'Basics of Electrical Engineering', 3, NULL, 3),
  ('2024_and_after', 'CSDS', 1, NULL, 'ES', 'ICT-105', 'System Modeling Techniques – I', 3, NULL, 3),
  ('2024_and_after', 'CSDS', 1, NULL, 'ES', 'ICT-107', 'Engineering Mechanics', 3, NULL, 3),
  ('2024_and_after', 'CSDS', 1, NULL, 'AEC', 'ICT-109', 'Communication Skills', 3, NULL, 3),
  ('2024_and_after', 'CSDS', 1, NULL, 'VAC', 'HVEE-113', 'Human Values & Ethics1+', 2, NULL, 2),
  ('2024_and_after', 'CSDS', 1, NULL, NULL, 'ICT-111', 'PCB design', 3, NULL, 3),
  ('2024_and_after', 'CSDS', 1, NULL, NULL, 'ICT-121', 'Introduction to Manufacturing Process', 3, NULL, 3),
  ('2024_and_after', 'CSDS', 1, NULL, 'ES', 'ICT-151', 'Programming for Problem Solving Lab', NULL, 2, 1),
  ('2024_and_after', 'CSDS', 1, NULL, 'ES', 'ICT-153', 'Basics of Electrical Engineering Lab', NULL, 2, 1),
  ('2024_and_after', 'CSDS', 1, NULL, 'VAC', 'ICT-352', 'NSS/NCC/Cultural Clubs/Technical Society/ Technical Club/Institution’s Innovation Council', NULL, NULL, 2),
  ('2024_and_after', 'CSDS', 2, NULL, 'ES', 'ICT-102', 'Data Structures', 3, NULL, 3),
  ('2024_and_after', 'CSDS', 2, NULL, 'SEC', 'ICT-104', 'Python Programming', 3, NULL, 3),
  ('2024_and_after', 'CSDS', 2, NULL, 'ES', 'ICT-106', 'Digital Electronics and Computer Organization', 3, NULL, 3),
  ('2024_and_after', 'CSDS', 2, NULL, 'ES', 'ICT-108', 'System Modeling Techniques - II', 3, NULL, 3),
  ('2024_and_after', 'CSDS', 2, NULL, 'ES', 'ICT-110', 'Semiconductor Engineering and its applications', 3, NULL, 3),
  ('2024_and_after', 'CSDS', 2, NULL, 'VAC', 'ICT-112', 'Environment Studies#+', 2, NULL, 2),
  ('2024_and_after', 'CSDS', 2, NULL, 'ES', 'ICT-152', 'Data Structures Lab', NULL, 2, 1),
  ('2024_and_after', 'CSDS', 2, NULL, 'SEC', 'ICT-154', 'Python Programming Lab', NULL, 2, 1),
  ('2024_and_after', 'CSDS', 2, NULL, 'ES', 'ICT-156', 'Digital Electronics and Computer Organization Lab', NULL, 2, 1),
  ('2024_and_after', 'CSDS', 2, NULL, 'ES', 'ICT-158', 'System Modeling Techniques Lab', NULL, 2, 1),
  ('2024_and_after', 'CSDS', 2, NULL, 'ES', 'ICT-160', 'Semiconductor Engineering and its applications lab', NULL, 2, 1),
  ('2024_and_after', 'CSDS', 3, NULL, 'PC', 'ICT-201', 'Foundations of Computer Science', 4, NULL, 4),
  ('2024_and_after', 'CSDS', 3, NULL, 'PC', 'ICT-203', 'Database Management Systems', 3, NULL, 3),
  ('2024_and_after', 'CSDS', 3, NULL, 'PC', 'ICT-205', 'Object Oriented Programming using C++', 3, NULL, 3),
  ('2024_and_after', 'CSDS', 3, NULL, 'PC', 'ICT-207', 'Design and Analysis of Algorithms', 3, NULL, 3),
  ('2024_and_after', 'CSDS', 3, NULL, NULL, 'ICT-217T', 'Digital Signal processing - I', 2, NULL, 2),
  ('2024_and_after', 'CSDS', 3, NULL, NULL, 'ICT-217P', 'Digital Signal Processing Laboratory - I', NULL, 2, 1),
  ('2024_and_after', 'CSDS', 3, NULL, NULL, 'ICT-219T', 'Digital System Design – I', 2, NULL, 2),
  ('2024_and_after', 'CSDS', 3, NULL, NULL, 'ICT-219P', 'Digital System Design – I Lab', NULL, 2, 1),
  ('2024_and_after', 'CSDS', 3, NULL, NULL, 'ICT-221', 'Engineering Electromagnetics', 3, NULL, 3),
  ('2024_and_after', 'CSDS', 3, NULL, NULL, 'ICT-223T', 'Microprocessor and Interfacing - I', 2, NULL, 2),
  ('2024_and_after', 'CSDS', 3, NULL, NULL, 'ICT-223P', 'Microprocessor and Interfacing – I Laboratory', NULL, 2, 1),
  ('2024_and_after', 'CSDS', 3, NULL, 'BS', 'ICT-209', 'Engineering Physics', NULL, NULL, NULL),
  ('2024_and_after', 'CSDS', 3, NULL, 'BS', 'ICT-211', 'Engineering Chemistry', NULL, NULL, NULL),
  ('2024_and_after', 'CSDS', 3, NULL, 'PCE', 'ICT-213', 'Computational Methods', NULL, NULL, NULL),
  ('2024_and_after', 'CSDS', 3, NULL, 'PCE', 'ICT-215', 'Computer Graphics', NULL, NULL, NULL),
  ('2024_and_after', 'CSDS', 3, NULL, 'PC', 'ICT-251', 'Database Management Systems Lab', NULL, 2, 1),
  ('2024_and_after', 'CSDS', 3, NULL, 'PC', 'ICT-253', 'Object Oriented Programming using C++', NULL, 2, 1),
  ('2024_and_after', 'CSDS', 3, NULL, 'PC', 'ICT-255', 'Design and Analysis of Algorithms Lab', NULL, 2, 1),
  ('2024_and_after', 'CSDS', 3, NULL, 'BS', 'ICT-257', 'Engineering Chemistry Lab', NULL, NULL, NULL),
  ('2024_and_after', 'CSDS', 3, NULL, 'BS', 'ICT-259', 'Engineering Physics Lab', NULL, NULL, NULL),
  ('2024_and_after', 'CSDS', 3, NULL, 'PCE', 'ICT-261', 'Computational Methods Lab', NULL, NULL, NULL),
  ('2024_and_after', 'CSDS', 3, NULL, 'PCE', 'ICT-263', 'Computer Graphics Lab', NULL, NULL, NULL),
  ('2024_and_after', 'CSDS', 4, NULL, 'PC', 'ICT-202', 'Theory of Computation', 3, NULL, 3),
  ('2024_and_after', 'CSDS', 4, NULL, 'PC', 'ICT-204', 'Probability and Stochastic Systems for Engineers', 3, NULL, 3),
  ('2024_and_after', 'CSDS', 4, NULL, 'PC', 'ICT-206', 'Computer Networks', 3, NULL, 3),
  ('2024_and_after', 'CSDS', 4, NULL, 'PC', 'ICT-208', 'Operating Systems', 3, NULL, 3),
  ('2024_and_after', 'CSDS', 4, NULL, NULL, 'ICT-214T', 'Digital Signal Processing – II', 2, NULL, 2),
  ('2024_and_after', 'CSDS', 4, NULL, NULL, 'ICT-214P', 'Digital Signal Processing – II Laboratory', NULL, 2, 1),
  ('2024_and_after', 'CSDS', 4, NULL, NULL, 'ICT-216T', 'Digital System Design – II', 2, NULL, 2),
  ('2024_and_after', 'CSDS', 4, NULL, NULL, 'ICT-216P', 'Digital System Design – II Lab', NULL, 2, 1),
  ('2024_and_after', 'CSDS', 4, NULL, NULL, 'ICT-218', 'Introduction to Robotics', 3, NULL, 3),
  ('2024_and_after', 'CSDS', 4, NULL, NULL, 'ICT-220T', 'Microprocessor and Interfacing – II', 2, NULL, 2),
  ('2024_and_after', 'CSDS', 4, NULL, NULL, 'ICT-220P', 'Microprocessor and Interfacing – II Laboratory', NULL, 2, 1),
  ('2024_and_after', 'CSDS', 4, NULL, 'VAC', 'ICT-210', 'Science and Practice of Happiness2', NULL, NULL, 2),
  ('2024_and_after', 'CSDS', 4, NULL, 'AEC', 'ICT-212', 'Scientific Writing', 2, NULL, 2),
  ('2024_and_after', 'CSDS', 4, NULL, 'PC', 'ICT-252', 'Computer Networks Lab', NULL, 2, 1),
  ('2024_and_after', 'CSDS', 4, NULL, 'PC', 'ICT-254', 'Operating Systems Lab', NULL, 2, 1),
  ('2024_and_after', 'CSDS', 5, NULL, 'PC', 'ICT-301', 'Compiler Design', 3, NULL, 3),
  ('2024_and_after', 'CSDS', 5, NULL, 'PC', 'ICT-303', 'Java Programming', 3, NULL, 3),
  ('2024_and_after', 'CSDS', 5, NULL, 'SEC', 'ICT-305', 'Web Development', 3, NULL, 3),
  ('2024_and_after', 'CSDS', 5, NULL, 'PC', 'ICT-311', 'Introduction to Data Analytics & Data Visualization', 3, NULL, 3),
  ('2024_and_after', 'CSDS', 5, NULL, 'PC', 'ICT-309', 'Fundamentals of Machine Learning & Neural Networks', 3, NULL, 3),
  ('2024_and_after', 'CSDS', 5, NULL, 'PC', 'ICT-323', 'Compiler Design Lab', NULL, 2, 1),
  ('2024_and_after', 'CSDS', 5, NULL, 'PC', 'ICT-325', 'Java Programming Lab', NULL, 2, 1),
  ('2024_and_after', 'CSDS', 5, NULL, 'SEC', 'ICT-327', 'Web Development Lab', NULL, 2, 1),
  ('2024_and_after', 'CSDS', 5, NULL, 'PC', 'ICT-333', 'Introduction to Data Analytics & Data Visualization', NULL, 2, 1),
  ('2024_and_after', 'CSDS', 5, NULL, 'PC', 'ICT-331', 'Fundamentals of Machine Learning & Neural Networks Lab', NULL, 2, 1),
  ('2024_and_after', 'CSDS', 5, NULL, 'AEC', 'ICT-321', 'Summer Training (after 4th Semester) Report and Presentation', NULL, NULL, 2),
  ('2024_and_after', 'CSDS', 5, NULL, 'AEC', 'ICT-349', 'Summer Project (after 4th Semester) Report and Presentation', NULL, NULL, 2),
  ('2024_and_after', 'CSDS', 6, NULL, 'PC', 'ICT-302', 'Software Engineering', 3, NULL, 3),
  ('2024_and_after', 'CSDS', 6, NULL, 'PC', 'ICT-304', 'Optimization Techniques for Machine Learning', 3, NULL, 3),
  ('2024_and_after', 'CSDS', 6, NULL, 'PC', 'ICT-306', 'Deep Learning', 3, NULL, 3),
  ('2024_and_after', 'CSDS', 6, NULL, 'PC', 'ICT-312', 'Big Data Systems and Scalable Analytics', 3, NULL, 3),
  ('2024_and_after', 'CSDS', 6, NULL, 'PC', 'ICT-314', 'Data Warehousing and Business Intelligence', 3, NULL, 3),
  ('2024_and_after', 'CSDS', 6, NULL, 'PC', 'ICT-324', 'Software Engineering Lab', NULL, 2, 1),
  ('2024_and_after', 'CSDS', 6, NULL, 'PC', 'ICT-326', 'Optimization Techniques for Machine Learning Lab', NULL, 2, 1),
  ('2024_and_after', 'CSDS', 6, NULL, 'PC', 'ICT-328', 'Deep Learning Techniques Lab', NULL, 2, 1),
  ('2024_and_after', 'CSDS', 6, NULL, 'PC', 'ICT-334', 'Big Data Systems and Scalable Analytics Lab', NULL, 2, 1),
  ('2024_and_after', 'CSDS', 6, NULL, 'PC', 'ICT-336', 'Data Warehousing and Business Intelligence Lab', NULL, 2, 1),
  ('2024_and_after', 'CSDS', 6, NULL, 'VAC', 'ICT-322', 'NSS/NCC/Cultural Clubs/Technical Society/ Technical Club/Institution’s Innovation Council', NULL, NULL, 2),
  ('2024_and_after', 'CSDS', 7, 'Regular', 'PC', 'ICT-421T', 'Data Mining and Business Intelligence', 3, NULL, 3),
  ('2024_and_after', 'CSDS', 7, 'Regular', NULL, 'ICT-421P', 'Business Intelligence Lab', NULL, 2, 1),
  ('2024_and_after', 'CSDS', 7, 'Regular', 'PC', 'ICT-423T', 'Time Series and Sequential Data Analysis', 3, NULL, 3),
  ('2024_and_after', 'CSDS', 7, 'Regular', NULL, 'ICT-423P', 'Time Series and Sequential Data Analysis Lab', NULL, 2, 1),
  ('2024_and_after', 'CSDS', 7, 'Regular', 'PC', 'ICT-403', 'Minor Project - Report', NULL, NULL, 4),
  ('2024_and_after', 'CSDS', 7, 'Regular', 'AEC', 'ICT-321', 'Summer Training (after 6th Semester) Report and Presentation', NULL, NULL, 2),
  ('2024_and_after', 'CSDS', 7, 'Regular', 'AEC', 'ICT-349', 'Summer Project (after 6th Semester) Report and Presentation', NULL, NULL, 2),
  ('2024_and_after', 'CSDS', 7, 'Research', 'PC / Internship', 'ICT-411', 'Research Work Report – I #', NULL, NULL, 14),
  ('2024_and_after', 'CSDS', 7, 'Research', NULL, 'ICT-413', 'Research Work – I Viva Voce', NULL, NULL, 4),
  ('2024_and_after', 'CSDS', 7, 'Research', NULL, 'ICT-415', 'Research Work – I Progress Evaluation', NULL, NULL, 2),
  ('2024_and_after', 'CSDS', 7, 'Research', 'AEC', 'ICT-401', 'Summer Training (after 6th Semester) Report and Presentation', NULL, NULL, 2),
  ('2024_and_after', 'CSDS', 7, 'Research', 'AEC', 'ICT-449', 'Summer Project (after 6th Semester) Report and Presentation', NULL, NULL, 2),
  ('2024_and_after', 'CSDS', 8, 'Regular', 'PC / Project', 'ICT-402', 'Major Project – Report', NULL, NULL, 16),
  ('2024_and_after', 'CSDS', 8, 'Regular', NULL, 'ICT-404', 'Major Project Viva Voce', NULL, NULL, 4),
  ('2024_and_after', 'CSDS', 8, 'Regular', NULL, 'ICT-406', 'Major Project Progress Evaluation', NULL, NULL, 2),
  ('2024_and_after', 'CSDS', 8, 'Research', 'PC / Internship', 'ICT-414', 'Thesis', NULL, NULL, 16),
  ('2024_and_after', 'CSDS', 8, 'Research', NULL, 'ICT-416', 'Internship Viva Voce', NULL, NULL, 4),
  ('2024_and_after', 'CSDS', 8, 'Research', NULL, 'ICT-418', 'Internship Progress Evaluation', NULL, NULL, 2);